name: el_meu_diec
description: El meu DIEC.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.22.0

dependencies:
  diacritic: ^0.1.6
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.11
  html: ^0.15.5
  http: ^1.2.2
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  share_plus: ^10.1.1
  supabase_flutter: ^2.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - .env.local

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
