name: el_meu_diec
description: El meu DIEC.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ^3.16.0

dependencies:
  diacritic: ^0.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  html: ^0.15.4
  http: ^1.2.0
  modal_bottom_sheet: ^3.0.0-pre
  provider: ^6.1.1
  share_plus: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic
