export 'src/model/autocomplete_entries.dart';
export 'src/model/autocomplete_entry.dart';
export 'src/model/bookmark_collection.dart';
export 'src/model/definition_entry_sense.dart';
export 'src/model/definition_entry_senses.dart';
export 'src/model/gender.dart';
export 'src/model/scope.dart';
export 'src/model/word.dart';
export 'src/model/word_cache.dart';
